workflows:
  ios-app-store:
    name: iOS App Store Release
    max_build_duration: 60
    instance_type: mac_mini_co2
    integrations:
      # Codemagic paneli 'Integrations' kısmında Apple Developer hesabınızı hangi isimle eklediyseniz onu yazmalısınız.
      # Varsayılan olarak 'Apple Developer Account' yazılmıştır.
      app_store_connect: Apple Developer Account
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          target_denied: false
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # App Store Connect'te uygulamanızı oluşturduktan sonra "App Information" (Uygulama Bilgisi) sayfasında yer alan
        # 10 haneli "Apple ID" (Uygulama Kimliği) numarasını buraya yazın.
        # Örnek: APP_STORE_APPLE_ID: 6470000000
        APP_STORE_APPLE_ID: 1234567890
    scripts:
      - name: Set up CocoaPods and Dependencies
        script: |
          flutter precache --ios
          flutter pub get
          cd ios && pod install --repo-update
      - name: Flutter Build IPA
        script: |
          # Codemagic kod imzalama işlemini otomatik yapacağı için --no-codesign parametresi kullanılmıştır.
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - imyesilyurt1677@hotmail.com # Derleme sonucu bu e-postaya gönderilir
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true # Derleme başarılı olunca otomatik TestFlight'a yükler
        submit_to_app_store: false # App Store incelemesine otomatik göndermez (manuel başlatmanız için)
